name: 'renewable_energy_data'
version: '1.0.0'
profile: 'renewable_energy_data'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  is_dev: false
  dev_days: 30

models:
  renewable_energy_data:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: table
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts

seeds:
  renewable_energy_data:
    country_reference:
      +column_types:
        country_code: string
        country_name: string
        capital_city: string
        latitude: float64
        longitude: float64
        population: int64
        is_eu_member: boolean
        brell_member_pre2025: boolean
        eu_target_2030_pct: float64
    country_group_membership:
      +column_types:
        country_code: string
        group_name: string
        group_description: string
